-- Flyway V4: seed from scripts/data/monolith-full-dump.sql
-- Imported from monolith dump
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM nguoi_dung WHERE id > 0;
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (1, 'hongnhunga', 'hongnhung@examplee.com', '$2a$10$WEi.lNJlIL9YRq/XG2whiO0G.2pd9PhEzIeNpr6iKrFMLmJ.T5A9q', 'USER', '2025-10-13 15:42:35', 'Nguyễn Thị Hồng Nhung', 0916928559, 'LOCAL', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (2, 'nguyenvana', 'nvana@example.com', '$2a$10$WEi.lNJlIL9YRq/XG2whiO0G.2pd9PhEzIeNpr6iKrFMLmJ.T5A9q', 'USER', '2025-10-13 15:42:35', 'Nguyễn Văn An ', NULL, 'LOCAL', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (3, 'tranthuan', 'tranthuan@example.com', '$2a$10$WEi.lNJlIL9YRq/XG2whiO0G.2pd9PhEzIeNpr6iKrFMLmJ.T5A9q', 'USER', '2025-10-13 15:42:35', 'Trần Thanh Tuấn', NULL, 'LOCAL', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (4, 'llan_4', 'lla@example.com', '$2a$10$WEi.lNJlIL9YRq/XG2whiO0G.2pd9PhEzIeNpr6iKrFMLmJ.T5A9q', 'USER', '2025-10-13 15:42:35', 'Lưu Thị Lan Anh', 0916928559, 'LOCAL', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (5, 'lethuy', 'lethuy@example.com', '$2a$10$WEi.lNJlIL9YRq/XG2whiO0G.2pd9PhEzIeNpr6iKrFMLmJ.T5A9q', 'USER', '2025-10-13 15:42:35', 'Lê Thị Thủy', NULL, 'LOCAL', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (6, 'phamanh', 'phamanh@example.com', '$2a$10$WEi.lNJlIL9YRq/XG2whiO0G.2pd9PhEzIeNpr6iKrFMLmJ.T5A9q', 'USER', '2025-10-13 15:42:35', 'Phạm Ngọc Anh', NULL, 'LOCAL', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (7, 'phamthuy', 'phamthuy@example.com', '$2a$10$WEi.lNJlIL9YRq/XG2whiO0G.2pd9PhEzIeNpr6iKrFMLmJ.T5A9q', 'USER', '2025-10-13 15:42:35', 'Phạm Thanh Thúy', NULL, 'LOCAL', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (8, 'khanhleo', 'khanhleo@example.com', '$2a$10$WEi.lNJlIL9YRq/XG2whiO0G.2pd9PhEzIeNpr6iKrFMLmJ.T5A9q', 'USER', '2025-10-13 15:42:35', 'Khánh Lê Messi', NULL, 'LOCAL', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (9, 'duczaki', 'duczaki@bookingtour.local', '$2a$10$FLHI4lWS7zpHjJrWZ38YHe8GWpdHo9Jc5zgv0L.fAvcyEPXXTULF6', 'ADMIN', '2025-10-13 15:42:35', 'Nguyễn Minh Đức', 0866147595, 'LOCAL', '/anh/user/50349fc3-78be-413b-b250-28d2af408092_c7e90d43-28a7-45a7-a0a4-f5b42b3d2798.png', 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (11, 'nvhuwng', 'nvh234205@gmail.com', 123456, 'USER', '2026-03-09 07:28:28', 'Ngô Văn Hưng', 0352674198, 'LOCAL', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (19, 'minhd4360@gmail.com', 'minhd4360@gmail.com', '$2a$10$FLHI4lWS7zpHjJrWZ38YHe8GWpdHo9Jc5zgv0L.fAvcyEPXXTULF6', 'USER', '2026-03-11 23:25:10', 'Đức zaki', NULL, 'GOOGLE', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (20, 'dduc97659@gmail.com', 'dduc97659@gmail.com', NULL, 'USER', '2026-03-11 23:26:01', 'duc duc', NULL, 'GOOGLE', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (21, 'facebook_1646175743402967', 'user21@import.local', NULL, 'USER', '2026-03-11 23:26:24', 'Minh Đức', NULL, 'FACEBOOK', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT INTO nguoi_dung (id, ten_dang_nhap, email, mat_khau, vai_tro, ngay_tao, ho_ten, number, provider, anh_dai_dien, enabled) VALUES (22, '23010634@st.phenikaa-uni.edu.vn', '23010634@st.phenikaa-uni.edu.vn', NULL, 'USER', '2026-03-12 00:07:40', 'Duc Nguyen Minh', NULL, 'GOOGLE', NULL, 1) ON DUPLICATE KEY UPDATE ho_ten=VALUES(ho_ten), number=VALUES(number), provider=VALUES(provider), anh_dai_dien=VALUES(anh_dai_dien);
INSERT IGNORE INTO nguoi_dung (ten_dang_nhap, email, mat_khau, vai_tro, ho_ten, provider, enabled) VALUES ('admin', 'admin@bookingtour.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ADMIN', 'Administrator', 'LOCAL', 1);
SET FOREIGN_KEY_CHECKS = 1;
