-- Flyway V4: seed from scripts/data/monolith-full-dump.sql
-- Imported from monolith dump
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM lich_trinh;
DELETE FROM ngay_khoi_hanh;
DELETE FROM chuyen_di_diem_don;
DELETE FROM chuyen_di;
DELETE FROM noi_luu_tru;
DELETE FROM phuong_tien;
DELETE FROM diem_don;
DELETE FROM diem_den;
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (1, 'Hà Nội', 'Việt Nam — Á Đông', '/anh/diemden/hanoi.jpg', 'Việt Nam', 1);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (2, 'Đà Nẵng', 'Việt Nam — Á Đông', '/anh/diemden/danang.jpg', 'Việt Nam', 1);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (3, 'Huế', 'Việt Nam — Á Đông', '/anh/diemden/hue.jpg', 'Việt Nam', 0);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (4, 'Hạ Long', 'Việt Nam — Á Đông', '/anh/diemden/halong.jpg', 'Việt Nam', 1);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (5, 'Nha Trang', 'Việt Nam — Á Đông', '/anh/diemden/nhatrang.jpg', 'Việt Nam', 0);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (6, 'Phú Quốc', 'Việt Nam — Á Đông', '/anh/diemden/phuquoc.jpg', 'Việt Nam', 0);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (7, 'Sa Pa', 'Việt Nam — Á Đông', '/anh/diemden/sapa.jpg', 'Việt Nam', 1);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (8, 'Cần Thơ', 'Việt Nam — Á Đông', '/anh/diemden/cantho.jpg', 'Việt Nam', 0);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (9, 'Bắc Kinh', 'Trung Quốc — Á Đông', '/anh/diemden/backinh.jpg', 'Trung Quốc', 0);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (10, 'Thượng Hải', 'Trung Quốc — Á Đông', '/anh/diemden/thuonghai.jpg', 'Trung Quốc', 1);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (11, 'Trương Gia Giới', 'Trung Quốc — Á Đông', '/anh/diemden/truonggiagioi.jpg', 'Trung Quốc', 0);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (12, 'Tokyo', 'Nhật Bản — Á Đông', '/anh/diemden/tokyo.jpg', 'Nhật Bản', 1);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (13, 'Kyoto', 'Nhật Bản — Á Đông', '/anh/diemden/kyoto.jpg', 'Nhật Bản', 0);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (14, 'Osaka', 'Nhật Bản — Á Đông', '/anh/diemden/osaka.jpg', 'Nhật Bản', 0);
INSERT INTO diem_den (id, ten, mo_ta, hinh_anh, vung_mien, noi_bat) VALUES (15, 'Seoul', 'Hàn Quốc — Á Đông', '/anh/diemden/seoul.jpg', 'Hàn Quốc', 0);
INSERT INTO diem_don (id, ten, dia_chi, thanh_pho) VALUES (1, 'Hà Nội', 'Hà Nội', 'Hà Nội');
INSERT INTO diem_don (id, ten, dia_chi, thanh_pho) VALUES (2, 'Hồ Chí Minh', 'Hồ Chí Minh', 'Hồ Chí Minh');
INSERT INTO diem_don (id, ten, dia_chi, thanh_pho) VALUES (3, 'Đà Nẵng', 'Đà Nẵng', 'Đà Nẵng');
INSERT INTO phuong_tien (id, ten, loai, icon) VALUES (1, 'Vietnam Airlines', 'Plane', 'bi-airplane');
INSERT INTO phuong_tien (id, ten, loai, icon) VALUES (2, 'Vietjet', 'Plane', 'bi-airplane');
INSERT INTO phuong_tien (id, ten, loai, icon) VALUES (3, 'SinhCafe Bus', 'Bus', 'bi-bus-front');
INSERT INTO phuong_tien (id, ten, loai, icon) VALUES (4, 'Vietjet', 'Plane', 'bi-airplane');
INSERT INTO phuong_tien (id, ten, loai, icon) VALUES (5, 'China Eastern', 'Plane', 'bi-airplane');
INSERT INTO phuong_tien (id, ten, loai, icon) VALUES (6, 'ANA', 'Plane', 'bi-airplane');
INSERT INTO phuong_tien (id, ten, loai, icon) VALUES (7, 'Local Bus', 'Bus', 'bi-bus-front');
INSERT INTO phuong_tien (id, ten, loai, icon) VALUES (8, 'Korean Air', 'Plane', 'bi-airplane');
INSERT INTO phuong_tien (id, ten, loai, icon) VALUES (9, 'Ferry Phu Quoc', 'Plane', 'bi-airplane');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (1, 'Khách sạn Hà Nội 1', 'Hoàn Kiếm, Hà Nội', 4, 'Hotel');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (2, 'Nhà nghỉ Hà Nội giá rẻ', 'Tây Hồ, Hà Nội', 3, 'Homestay');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (3, 'Sunrise Đà Nẵng Hotel', 'Mỹ Khê, Đà Nẵng', 4, 'Hotel');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (4, 'Apartment Đà Nẵng Center', 'Hải Châu, Đà Nẵng', 3, 'Apartment');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (5, 'Khách sạn Huế River', 'Huế', 4, 'Hotel');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (6, 'Resort Hạ Long Bay', 'Hạ Long', 5, 'Resort');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (7, 'Hotel Nha Trang Beach', 'Nha Trang', 4, 'Hotel');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (8, 'Resort Phú Quốc 5*', 'Phú Quốc', 5, 'Resort');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (9, 'Homestay Sa Pa View', 'Sa Pa', 3, 'Homestay');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (10, 'Khách sạn Cần Thơ Riverside', 'Cần Thơ', 4, 'Hotel');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (11, 'Beijing Grand Hotel', 'Bắc Kinh', 4, 'Hotel');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (12, 'Shanghai River Hotel', 'Thượng Hải', 4, 'Hotel');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (13, 'Zhangjiajie Inn', 'Trương Gia Giới', 2, 'Inn');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (14, 'Tokyo Central Hotel', 'Tokyo', 4, 'Hotel');
INSERT INTO noi_luu_tru (id, ten, dia_chi, hang_sao, loai) VALUES (15, 'Seoul Cozy Stay', 'Seoul', 4, 'Hotel');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (1, 'Tour Hà Nội 3N2Đ', 'Tham quan Hồ Gươm, Văn Miếu, Lăng Bác', 2500000.00, '2026-03-18', '2026-03-25', 1, 3, 1, 1, 1, '/anh/chuyendi/hanoi.jpg', 'Khám phá chiều sâu văn hóa của "Thủ đô ngàn năm văn hiến". Quý khách sẽ có những phút giây lắng đọng tại Lăng Bác, tìm hiểu lịch sử tại Văn Miếu - Quốc Tử Giám. Đặc biệt, trải nghiệm Xích lô dạo quanh 36 phố phường vào buổi xế chiều và thưởng thức ẩm thực tinh tế như Phở Thìn, Chả cá Lã Vọng sẽ là ký ức khó quên.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (2, 'Tour 4N3Đ Đà Nẵng - Hội An', 'Bà Nà Hill, Hội An cổ', 4200000.00, '2026-03-17', '2026-03-20', 2, 1, 3, NULL, 1, '/anh/diemden/danang.jpg', 'Hành trình xuyên qua những vùng đất di sản. Chạm tay vào "mây ngàn" tại Bà Nà Hills với cây Cầu Vàng biểu tượng. Khi màn đêm buông xuống, quý khách sẽ được thả mình vào không gian lung linh của Phố cổ Hội An, tự tay thả hoa đăng trên sông Hoài và thưởng thức show diễn "Ký ức Hội An" đẳng cấp thế giới.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (3, 'Khám phá Huế 2N1Đ', 'Ăn uống cung đình, sông Hương', 1800000.00, '2026-03-09', '2026-03-15', 3, 1, 5, NULL, 1, '/anh/diemden/hue.jpg', 'Trở về không gian triều đình phong kiến với hệ thống Đại Nội và các lăng tẩm uy nghi (Lăng Tự Đức, Khải Định). Điểm khác biệt chính là trải nghiệm Nghe ca Huế trên sông Hương và thưởng thức "Cơm Vua" - nơi quý khách được hóa thân thành hoàng thân quốc thích trong bộ lễ phục triều đình.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (4, 'Hạ Long Bay 2N1Đ', 'Du thuyền Vịnh Hạ Long', 3000000.00, '2026-03-03', '2026-03-04', 4, 4, 6, NULL, 0, '/anh/diemden/halong.jpg', 'Tận hưởng kỳ nghỉ dưỡng thượng lưu trên Du thuyền 5 sao. Quý khách sẽ được chèo thuyền Kayak xuyên qua các hang động đá vôi nghìn năm tuổi, đón bình minh với bài tập Tai-chi trên boong tàu và thưởng thức tiệc hải sản tươi sống giữa lòng di sản thiên nhiên thế giới.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (5, 'Nha Trang Beach Relax 3N', 'Tắm biển, lặn ngắm san hô', 3500000.00, '2026-03-03', '2026-03-05', 5, 3, 7, NULL, 0, '/anh/diemden/nhatrang.jpg', 'Sự kết hợp hoàn hảo giữa nhịp sống phố thị và sự tĩnh lặng của biển khơi. Tour tập trung vào việc tối ưu thời gian để quý khách vừa có thể check-in những biểu tượng của Thủ đô, vừa kịp lúc bắt trọn khoảnh khắc hoàng hôn buông trên vịnh biển từ những góc nhìn đẹp nhất.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (6, 'Phú Quốc Resort 4N', 'Resort 5*, câu cá, lặn', 7000000.00, '2026-03-14', '2026-03-16', 6, 9, 8, NULL, 0, '/anh/diemden/hue.jpg', 'Nghỉ dưỡng tại những bãi cát trắng mịn nhất Việt Nam. Chương trình tập trung vào trải nghiệm cá nhân hóa tại VinWonders, tắm bùn khoáng nóng thư giãn phục hồi sức khỏe và tham gia các trò chơi thể thao nước cảm giác mạnh như dù lượn, lặn ngắm san hô tại Vịnh San Hô.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (7, 'Sa Pa Trek 2N', 'Trekking bản làng, cáp treo', 2000000.00, '2025-05-30', '2025-06-01', 7, 7, 9, NULL, 0, '/anh/diemden/sapa.jpg', 'Một hành trình nghỉ dưỡng thực thụ tại các resort cao cấp. Điểm nhấn là chuyến Cáp treo vượt biển dài nhất thế giới đi hòn Thơm, khám phá "Thành phố không ngủ" Grand World và thưởng thức đặc sản bún quậy trứ danh cùng rượu sim nồng nàn.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (8, 'Cần Thơ Miền Tây 2N1Đ', 'Chợ nổi, miệt vườn', 1600000.00, '2026-03-04', '2026-03-06', 8, 1, 10, NULL, 1, '/anh/diemden/cantho.jpg', 'Sự giao thoa giữa hai vùng biển đẹp nhất Việt Nam. Quý khách sẽ thấy được sự khác biệt giữa vẻ đẹp hiện đại, năng động của Đà Nẵng và nét hoang sơ, thơ mộng của Phú Quốc. Đây là tour dành cho những tín đồ "cuồng biển" muốn chinh phục mọi cung đường xanh.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (9, 'Beijing City Tour 4N', 'Tường thành, Tử Cấm Thành', 1650000.00, '2025-10-01', '2025-10-05', 9, 5, 11, NULL, 0, '/anh/diemden/thuonghai.jpg', 'Chạm tay vào kỳ quan Vạn Lý Trường Thành, khám phá sự huyền bí của Tử Cấm Thành và thưởng thức món Vịt quay Bắc Kinh nguyên bản trong không gian cung đình xưa.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (10, 'Shanghai Highlights 3N', 'Tham quan Thượng Hải, Bến Thượng Hải', 1300000.00, '2026-03-11', '2026-03-13', 10, 5, 12, 1, 0, '/anh/chuyendi/shanghai.jpg', 'Tập trung vào nhịp sống sôi động bậc nhất Trung Hoa. Dạo bước trên phố đi bộ Nam Kinh, chiêm bái Dự Viên và tận hưởng sự lộng lẫy của các tòa nhà chọc trời về đêm.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (11, 'Zhangjiajie Nature 3N', 'Thiên nhiên Trương Gia Giới', 1800000.00, '2025-11-01', '2025-11-03', 11, 5, 13, NULL, 0, '/anh/diemden/hue.jpg', 'Lạc vào hành tinh Pandora ngoài đời thực với các cột đá cao vút tại Viên Gia Giới. Trải nghiệm cảm giác mạnh trên Cầu kính Đại Hiệp Cốc và đi thang máy Bách Lộ dài nhất thế giới.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (12, 'Tokyo Family 5N', 'Tokyo Disneyland, Asakusa', 2000000.00, '2026-03-03', '2026-03-07', 12, 6, 14, NULL, 0, '/anh/diemden/tokyo.jpg', 'Tour lý tưởng cho gia đình. Khám phá Disneyland thần tiên, giao lộ Shibuya sầm uất và trải nghiệm văn hóa Anime tại Akihabara cùng với hoạt động làm Sushi thủ công.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (13, 'Kyoto Culture 3N', 'Đền chùa, trà đạo', 1800000.00, '2026-03-03', '2026-03-05', 13, 6, 14, NULL, 0, '/anh/diemden/kyoto.jpg', 'Tìm về sự an yên tại các ngôi đền nghìn năm tuổi như Thanh Thủy Tự (Kiyomizu-dera). Điểm nhấn là đi bộ dưới hàng ngàn cổng Torii đỏ rực tại Fushimi Inari và gặp gỡ các nàng Geisha tại phố Gion.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (14, 'Osaka Food Tour 2N', 'Món ăn đường phố, Dotonbori', 1700000.00, '2025-12-11', '2025-12-12', 14, 6, 14, NULL, 0, '/anh/diemden/osaka.jpg', 'Thiên đường cho những tín đồ ẩm thực. Càn quét khu phố Dotonbori với Takoyaki, Okonomiyaki. Tham quan lâu đài Osaka uy nghiêm và khu vui chơi Universal Studios.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (15, 'Seoul City 4N', 'Mua sắm Myeongdong, palaces', 2800000.00, '2025-09-15', '2025-09-19', 15, 8, 15, NULL, 0, '/anh/diemden/seoul.jpg', 'Khám phá "Làn sóng Hallyu" tại thủ đô Hàn Quốc. Mặc Hanbok check-in cung điện Gyeongbokgung, mua sắm tại Myeongdong và ngắm toàn cảnh thành phố từ tháp Namsan lãng mạn.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (16, 'Hà Nội - Hạ Long 2N', 'Combo Hà Nội + Hạ Long', 3200000.00, '2026-03-03', '2026-03-05', 4, 4, 6, NULL, 0, '/anh/diemden/hanoi.jpg', 'Sự giao thoa giữa hai vùng biển đẹp nhất Việt Nam. Quý khách sẽ thấy được sự khác biệt giữa vẻ đẹp hiện đại, năng động của Đà Nẵng và nét hoang sơ, thơ mộng của Phú Quốc. Đây là tour dành cho những tín đồ "cuồng biển" muốn chinh phục mọi cung đường xanh.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (17, 'Đà Nẵng - Phú Quốc 5N', 'Đà Nẵng + Phú Quốc nghỉ dưỡng', 9000000.00, '2025-09-10', '2025-09-14', 6, 2, 8, NULL, 0, '/anh/diemden/phuquoc.jpg', 'Sự giao thoa giữa hai vùng biển đẹp nhất Việt Nam. Quý khách sẽ thấy được sự khác biệt giữa vẻ đẹp hiện đại, năng động của Đà Nẵng và nét hoang sơ, thơ mộng của Phú Quốc. Đây là tour dành cho những tín đồ "cuồng biển" muốn chinh phục mọi cung đường xanh.');
INSERT INTO chuyen_di (id, tieu_de, mo_ta, gia, ngay_khoi_hanh, ngay_ket_thuc, id_diem_den, id_phuong_tien, id_noi_luu_tru, id_diem_don, noi_bat, hinh_anh, highlight) VALUES (18, 'Tour Bắc Kinh - Thượng Hải 7N', 'Kết hợp Bắc Kinh và Thượng Hải', 2200000.00, '2026-03-03', '2026-03-05', 9, 5, 12, 1, 0, '/anh/chuyendi/backinh.jpg', 'Hành trình kết nối giữa quá khứ và tương lai. Từ vẻ cổ kính của cung điện Bắc Kinh đến sự xa hoa, hiện đại của Bến Thượng Hải và tháp truyền hình Minh Châu Phương Đông.');
INSERT IGNORE INTO chuyen_di_diem_don (chuyen_di_id, diem_don_id) VALUES (1, 1);
INSERT IGNORE INTO chuyen_di_diem_don (chuyen_di_id, diem_don_id) VALUES (10, 1);
INSERT IGNORE INTO chuyen_di_diem_don (chuyen_di_id, diem_don_id) VALUES (18, 1);
INSERT INTO lich_trinh (id, id_chuyen_di, ngay_thu, tieu_de, mo_ta) VALUES (1, 1, 1, 'TP. Cần Thơ - Nội Bài (Hà Nội) - Hạ Long', 'Quý khách tập trung tại Ga đi trong nước Sân bay Cần Thơ. Hướng dẫn viên làm thủ tục cho Quý khách đáp chuyến bay đi Hà Nội. Đến sân bay Nội Bài, xe khởi hành đưa Quý khách đến thành phố biển Hạ Long qua đường cao tốc Hải Phòng – Hạ Long, trên đường ngắm cảnh Bạch Đằng Giang. Đến nơi, xe đưa Quý khách ngắm Cầu Bãi Cháy và thành phố Hạ Long lung linh về đêm.rnrnQuý khách nhận phòng khách sạn nghỉ ngơi hay tự do khám phá nhiều hoạt động dịch vụ giải trí sôi nổi tại “phố cổ” Bãi Cháy - nằm cạnh công viên Sun World Hạ Long từ những ẩm thực đường phố đến các quán cà phê siêu dễ thương như Hòn Gai Coffee & Lounge hay thoải mái bung xõa tại The Mini Bar, Brothers Pub,..rnrnNghỉ đêm tại Hạ Long
02 bữa ăn (trưa, chiều)');
INSERT INTO lich_trinh (id, id_chuyen_di, ngay_thu, tieu_de, mo_ta) VALUES (2, 2, 1, 'Hạ Long - Ninh Bình ', 'Nghỉ đêm tại Ninh Bình
au khi ăn sáng, xe đưa Quý khách đến bến tàu bắt đầu hành trình du ngoạn Vịnh Hạ Long - Thắng cảnh thiên nhiên tuyệt đẹp và vô cùng sống động, được UNESCO công nhận là di sản thiên nhiên Thế giới năm 1994.rnĐộng Thiên Cung là một trong những động đẹp nhất ở Hạ Long. Vẻ đẹp nguy nga và lộng lẫy bởi những lớp thạch nhũ và những luồng ánh sáng lung linh.rnTừ trên tàu ngắm nhìn các hòn đảo lớn nhỏ trong Vịnh Hạ Long: Hòn Gà Chọi, Hòn Lư Hương.rnSau khi ăn trưa, Quý khách khởi hành đi Ninh Bình - vùng đất mệnh danh là “Nơi mơ đến, chốn mong về” với nhiều di tích văn hóa, thiên nhiên vô cùng đặc sắc. Đến nơi, quý khách chiêm bái Chùa Bái Đính - một quần thể chùa với nhiều kỷ lục Việt Nam như pho tượng phật Di Lặc bằng đồng nặng 80 tấn, hành lang với 500 tượng vị La Hán, tòa Bảo Tháp cao 99m…rn
03 bữa ăn (sáng, trưa, chiều)');
INSERT INTO lich_trinh (id, id_chuyen_di, ngay_thu, tieu_de, mo_ta) VALUES (3, 3, 1, 'Ninh bình -Di Sản Tràng An- Hà Nội', 'Nghỉ đêm tại Hà Nội
Quý khách ăn sáng và trả phòng khách sạn. Xe đưa Quý khách đi tham quan:rnrnKhu Du Lịch Tràng An: Quý khách lên thuyền truyền thống đi tham quan thắng cảnh hệ thống núi đá vôi hùng vĩ và các thung lũng ngập nước, thông với nhau bởi các dòng suối tạo nên các hang động ngập nước quanh năm. Điểm xuyến trong không gian hoang sơ, tĩnh lặng là hình ảnh rêu phong, cổ kính của các mái đình, đền, phủ nằm nép mình dưới chân các dãy núi cao.rnTuyệt Tịnh Cốc: nằm giữa mảnh đất cố đô Hoa Lư (Ninh Bình), động Am Tiên ẩn mình giữa lưng chừng núi được mệnh danh là “thiên đường nơi hạ giới” và được giới trẻ gọi là Tuyệt Tịnh Cốc Việt Nam.rnrnTiếp tục hành trình, Quý khách trở về Hà Nội nhận phòng khách sạn nghỉ nghơi hoặc tự do dạo 36 phố phường Hà Nội, trải nghiệm không gian sôi nổi, náo nhiệt tại Phố Tạ Hiện hay tìm một gốc với ly cà phê quan sát phố cổ hẳn cũng rất thú vị.rnrn
3 bữa ăn(sáng-trưa-chiều)');
INSERT INTO lich_trinh (id, id_chuyen_di, ngay_thu, tieu_de, mo_ta) VALUES (4, 1, 2, 'Tphcm – Sân Bay Nội Bài (Hà Nội) – Sapa ', 'Sapa.
Quý khách tập trung tại sân bay Tân Sơn Nhất (Ga nội địa), hướng dẫn viên hỗ trợ khách làm thủ tục đáp chuyến bay đi Hà Nội. Đến sân bay Nội Bài, xe và HDV Vietravel đón Quý khách đi khởi hànhtheo cao tốc Hà Nội – Lào Cai đưa Quý khách đến phố núi Sapa. Trên đường, Quý khách dùng cơm trưa tại nhà hàng địa phương. Đến nơi, Quý khách tham quan:rnrnBản Cát Cát - đẹp như một bức tranh giữa vùng phố cổ Sapa, nơi đây thu hút du khách bởi cầu treo, thác nước, guồng nước và những mảng màu hoa mê hoặc du khách khi lạc bước đến đây. Thăm những nếp nhà của người Mông, Dao, Giáy trong bản, du khách sẽ không khỏi ngỡ ngàng trước vẻ đẹp mộng mị của một trong những ngôi làng cổ đẹp nhất Sapa.
02 bữa (Trưa, Chiều)');
INSERT INTO lich_trinh (id, id_chuyen_di, ngay_thu, tieu_de, mo_ta) VALUES (5, 2, 2, 'Sapa – Fansipan Legend – Đèo Ô Quy Hồ', 'Sapa
Quý khách dùng điểm tâm sáng tại khách sạn. xe đưa đoàn ra ga Sapa, Quý khách trải nghiệm đến khu du lịch Fansipan Legend bằng Tàu hỏa leo núi Mường Hoa hiện đại nhất Việt Nam với tổng chiều dài gần 2000m, thưởng ngoạn bức tranh phong cảnh đầy màu sắc của cánh rừng nguyên sinh, thung lũng Mường Hoa.rnrnChinh phục đỉnh núi Fansipan với độ cao 3.143m hùng vĩ bằng cáp treo (chi phí tự túc).rnLễ Phật tại chùa Trình hay cầu phúc lộc, bình an cho gia đình tại Bích Vân Thiền Tự trong hệ thống cảnh quan tâm linh trên đỉnh Fansipan.rnQuý khách dùng cơm tối tại Sapa và tự do nghỉ ngơi.
03 bữa ăn (sáng, trưa, chiều)');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (10, 3, '2026-03-09', '2026-03-11', 2, 0, 600000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (11, 3, '2026-03-10', '2026-03-13', 2, 0, 2200000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (12, 3, '2026-03-26', '2026-03-29', 2, 0, 2800000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (13, 5, '2026-05-02', '2026-05-05', 1, 0, 300000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (17, 3, '2026-03-03', '2026-03-04', 3, 0, 1454000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (19, 3, '2026-03-03', '2026-03-07', 12, 0, 1454000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (20, 3, '2026-03-11', '2026-03-14', 12, 0, 1454000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (21, 3, '2026-03-03', '2026-03-05', 5, 0, 300000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (22, 3, '2026-03-06', '2026-03-09', 5, 0, 300000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (23, 3, '2026-03-11', '2026-03-13', 1, 0, 300000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (26, 3, '2026-03-04', '2026-03-11', 8, 0, 1454000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (27, 3, '2026-03-06', '2026-03-12', 18, 0, 1454000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (28, 3, '2026-03-18', '2026-03-20', 1, 0, 300000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (29, 3, '2026-03-20', '2026-03-22', 1, 0, 300000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (38, 3, '2026-03-18', '2026-03-20', 3, 0, 300000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (42, 3, '2026-03-12', '2026-03-14', 10, 0, NULL, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (43, 3, '2026-03-17', '2026-03-19', 3, 0, 300000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (50, 3, '2026-03-13', '2026-03-14', 3, 0, 300000, 'ACTIVE');
INSERT INTO ngay_khoi_hanh (id, id_chuyen_di, ngay_khoi_hanh, ngay_ket_thuc, so_cho_toi_da, so_cho_da_dat, gia_override, trang_thai) VALUES (52, 3, '2026-03-13', '2026-03-15', 2, 0, NULL, 'ACTIVE');
SET FOREIGN_KEY_CHECKS = 1;
